# Generated by Django 2.2.7 on 2019-12-09 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decorations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoration_name', models.CharField(max_length=200)),
                ('decoration_champion', models.CharField(max_length=50)),
                ('decoration_part', models.CharField(max_length=50)),
                ('decoration_rarelity', models.CharField(max_length=50)),
                ('decoration_average_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('publisher_id', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota2_deco.Decorations')),
            ],
        ),
    ]
